import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Foto Fokus Studio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="w-full h-screen bg-blue-600 flex flex-col items-center justify-center" style={{background: "linear-gradient(0deg, rgba(2,0,36,1) 0%, rgba(20,51,240,0.4906337535014006) 35%, rgba(0,212,255,1) 100%), url('https://warnaindonesiaphoto.com/wp-content/uploads/2020/07/studio-18-1.jpg')",backgroundPosition:"center", backgroundSize:"cover", backgroundRepeat: "no-repeat"}}>
        <h1 className="text-white font-bold text-6xl lg:text-8xl text-center drop-shadow-lg">Foto Fokus Studio</h1>
        <a href="" className="p-2 hover:bg-blue-400 text-white font-bold mt-3 border-2 rounded-md border-white">Reservasi</a>
      </main>
      <div className="w-full bg-blue-100 pt-4">
        <h1 className="font-bold text-2xl">Reservasi Sekarang</h1>
        <div className="w-80">
          <label for="price" class="block text-sm font-medium text-gray-700">
            Price
          </label>
          <div class="mt-1 relative rounded-md shadow-sm">
            <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
              <span class="text-gray-500 sm:text-sm"> $ </span>
            </div>
            <input
              type="text"
              name="price"
              id="price"
              class="focus:ring-indigo-500 focus:border-indigo-500 block w-full pl-7 pr-12 sm:text-sm border-gray-300 rounded-md"
              placeholder="0.00"
            />
            <div class="absolute inset-y-0 right-0 flex items-center">
              <label for="currency" class="sr-only">
                Currency
              </label>
              <select
                id="currency"
                name="currency"
                class="focus:ring-indigo-500 focus:border-indigo-500 h-full py-0 pl-2 pr-7 border-transparent bg-transparent text-gray-500 sm:text-sm rounded-md"
              >
                <option>USD</option>
                <option>CAD</option>
                <option>EUR</option>
              </select>
            </div>
          </div>
        </div>
      </div> 
    </div>
  );
}
